CREATE TABLE IF NOT EXISTS rekening (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nomor_rekening VARCHAR(16) NOT NULL,
  nama_penerima VARCHAR(80) NOT NULL,
  online_bank_code VARCHAR(3) NOT NULL,
  bank_tujuan VARCHAR(35) NOT NULL,
  aktif TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_rekening_nomor (nomor_rekening)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS kategori (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_kategori_nama (nama)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE belanja
  ADD COLUMN rekening_id INT NULL AFTER keterangan,
  ADD COLUMN kategori VARCHAR(100) NULL AFTER rekening_id,
  ADD CONSTRAINT fk_belanja_rekening FOREIGN KEY (rekening_id) REFERENCES rekening(id) ON DELETE SET NULL,
  ADD INDEX idx_belanja_kategori (kategori);

INSERT INTO rekening (nomor_rekening, nama_penerima, online_bank_code, bank_tujuan) VALUES
('154060000123', 'UD BERKAH MANDIRI', '114', 'BPD JAWA TIMUR'),
('154060000124', 'UD DIANA STORE', '114', 'BPD JAWA TIMUR'),
('154060000456', 'UD BASRI BERKAH JAYA', '114', 'BPD JAWA TIMUR'),
('154060000789', 'UD RUMAH SAYUR BONDOWOSO', '114', 'BPD JAWA TIMUR'),
('154060000321', 'UD NAURA STARS MANDIRI', '114', 'BPD JAWA TIMUR'),
('154060000654', 'UD USAHA BERKAH MANDIRI', '114', 'BPD JAWA TIMUR'),
('154060000987', 'UD ZELINA BAKERY', '114', 'BPD JAWA TIMUR'),
('154060000889', 'UD MERPATIQUU', '114', 'BPD JAWA TIMUR'),
('901184516100', 'MUNIF MUJIANTO', '535', 'PT BANK SEABANK INDONESIA'),
('1583713634', 'ACHMAD SHOLEHUDDIN', '114', 'BPD JAWA TIMUR');
