<?php

declare(strict_types=1);

use Phinx\Seed\AbstractSeed;

/**
 * Seed: isi app_version_changelog (versi aplikasi + changelog per role).
 *
 * CARA INSERT DATA CHANGELOG (tidak perlu buat file PHP baru):
 * 1. Buka file ini (ChangelogVersionSeed.php)
 * 2. Tambah baris baru di array $entries di bawah — format: app, version, role_id, title, changelog, released_at
 * 3. Simpan, lalu jalankan: php vendor/bin/phinx seed:run -s ChangelogVersionSeed
 *
 * Seed akan hapus dulu entri yang app+version sama, lalu insert semua (termasuk yang baru).
 * role_id: NULL = visible semua (public). role_id = id dari tabel role (1=super_admin, 2=admin_uwaba, ...).
 */
class ChangelogVersionSeed extends AbstractSeed
{
    /** Daftar entri changelog. Untuk rilis baru (mis. uwaba 6.2.3): tambah baris di sini, jangan buat file baru. */
    private array $entries = [
        // --- Backend (API) 1.0.0 - ringkasan ---
        ['app' => 'api', 'version' => '1.0.0', 'role_id' => null, 'title' => 'Backend API', 'changelog' => "Slim 4, PHP 7.4+\nAuth JWT, CORS, rate limit\nMigrasi & seed via Phinx (schema + RoleSeed, ChangelogVersionSeed)\nEndpoint GET /api/version (versi backend)\nEndpoint GET /api/version/changelog (changelog per app & role)\nPengaturan, Kalender, Hari Penting\nUWABA, Pembayaran, Santri, Users, Lembaga, Jabatan\nPSB, Pengeluaran, Pemasukan, Umroh, Ijin, Juara, WhatsApp, UGT", 'released_at' => '2026-02-24 00:00:00'],
        // --- Backend (API) 2.0.0 - routes migration, CORS, fix login 500 ---
        ['app' => 'api', 'version' => '2.0.0', 'role_id' => null, 'title' => 'Backend API 2.0.0', 'changelog' => "Migrasi routes: definisi route dipindah dari index.php ke api/routes/*.php (21 file). API v1 path tidak berubah.\nPreflight OPTIONS: penanganan awal di index.php + perbaikan CorsMiddleware agar login dari localhost:5173 tidak kena CORS.\nRoute files: tambah use statement untuk middleware & controller (perbaikan Class not found saat registrasi route).\nLogin v2: catch Throwable dan tampilkan pesan error di response (development) agar 500 mudah dilacak.\nFrontend: fallback base URL api/public/api (uwaba & daftar), .env.example & env.production (APP_ENV, APP_URL).\nDokumen: PLAN_ROUTES_MIGRATION.md (verifikasi), phinx.php (contoh migrate -e development).", 'released_at' => '2026-02-25 00:00:00'],
        // --- UWABA 6.2.2 (contoh dari seed_uwaba_6.2.2.sql) ---
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => 15, 'title' => 'Pendaftaran (PSB)', 'changelog' => "Dashboard Pendaftaran\nData Pendaftar\nPadukan Data\nPengaturan PSB\nItem & Manage Item Set\nManage Kondisi & Kondisi Registrasi\nAssign Item ke Set\nSimulasi\nImage Editor (crop/upload)", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => 16, 'title' => 'Pendaftaran (PSB)', 'changelog' => "Dashboard Pendaftaran\nData Pendaftar\nPadukan Data\nPengaturan PSB\nItem & Manage Item Set\nManage Kondisi & Kondisi Registrasi\nAssign Item ke Set\nSimulasi\nImage Editor (crop/upload)", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => 2, 'title' => 'Pembayaran (UWABA)', 'changelog' => "Dashboard Pembayaran\nInput pembayaran syahriah (UWABA)\nTunggakan\nKhusus\nManage Data pembayaran\nLaporan pembayaran\nImport Khusus & Import Tunggakan\nPrint kwitansi", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => 4, 'title' => 'Pembayaran (UWABA)', 'changelog' => "Dashboard Pembayaran\nInput pembayaran syahriah (UWABA)\nTunggakan\nKhusus\nManage Data pembayaran\nLaporan pembayaran\nImport Khusus & Import Tunggakan\nPrint kwitansi", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => null, 'title' => 'Keuangan', 'changelog' => "Dashboard Keuangan\nPengeluaran & Rencana Pengeluaran\nPemasukan\nAktivitas & Aktivitas Tahun Ajaran", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => 8, 'title' => 'Umroh', 'changelog' => "Dashboard Umroh\nJamaah Umroh\nTabungan Umroh\nLaporan Umroh", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => 9, 'title' => 'Umroh', 'changelog' => "Dashboard Umroh\nJamaah Umroh\nTabungan Umroh\nLaporan Umroh", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => 18, 'title' => 'Ijin & Juara', 'changelog' => "Dashboard Ijin\nData Ijin\nData Boyong\nData Juara", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => 19, 'title' => 'Ijin & Juara', 'changelog' => "Dashboard Ijin\nData Ijin\nData Boyong\nData Juara", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => 22, 'title' => 'Kalender', 'changelog' => "Kalender (Hijriah/Masehi)\nHari Penting\nPengaturan Kalender\nConverter tanggal", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => 1, 'title' => 'Pengaturan & User', 'changelog' => "Dashboard Umum\nManage Users & Edit User\nImport Users\nPengurus\nLembaga\nManage Jabatan\nManage Uploads\nProfil (lihat & edit)", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => null, 'title' => 'Akses Santri (Public)', 'changelog' => "Tampilan public untuk santri: Santri, UWABA, Khusus, Tunggakan, Ijin, Shohifah, Kalender (tanpa login)", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => 23, 'title' => 'UGT & Lainnya', 'changelog' => "Data Madrasah (UGT)\nLogin & role-based access\nSetup Akun / Ubah Password / Ubah Username (link dari WA)\nPWA & notifikasi push\nHeader staging (merah)", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => 1, 'title' => 'UGT & Lainnya', 'changelog' => "Data Madrasah (UGT)\nLogin & role-based access\nSetup Akun / Ubah Password / Ubah Username (link dari WA)\nPWA & notifikasi push\nHeader staging (merah)", 'released_at' => '2025-02-24 00:00:00'],
        // --- UWABA 6.3.5 - koneksi API, menu Koordinator, UGT, Kalender Pesantren, Setting ---
        ['app' => 'uwaba', 'version' => '6.3.5', 'role_id' => null, 'title' => 'Koneksi API & Login', 'changelog' => "Base URL API: fallback ke http://localhost/api/public/api (routes terbaru). .env.example: VITE_API_BASE_URL untuk local (api/public/api).\nPerbaikan CORS: preflight OPTIONS di backend agar login dari localhost:5173 tidak diblokir.\nVersi backend (BACKEND_VERSION): 2.0.0.", 'released_at' => '2026-02-25 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.3.5', 'role_id' => 23, 'title' => 'UGT: Koordinator & Data Madrasah', 'changelog' => "Menu Koordinator (admin_ugt, super_admin): halaman Kelola Koordinator, daftar pengurus dengan role koordinator, filter by role/lembaga/jabatan/status, tambah role koordinator, nonaktifkan (hapus) role koordinator.\nData Madrasah: filter koordinator, field ID Koordinator di form tambah/edit madrasah, Cari Koordinator offcanvas, koordinator terkunci untuk role koordinator_ugt (hanya lihat data sendiri).\nImport/Export madrasah: kolom koordinator, bulk edit ID Koordinator.", 'released_at' => '2026-02-25 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.3.5', 'role_id' => 1, 'title' => 'UGT & Kalender Pesantren', 'changelog' => "UGT: Menu Koordinator, Data Madrasah dengan filter koordinator dan assign koordinator ke madrasah.\nKalender Pesantren (super_admin): menu Jadwal Pesantren, Kelola Event, Pengaturan Google Kalender.\nSetting: menu Role & Akses, Fitur (navMenuConfig).\nKeuangan: menu Aktivitas TA (Aktivitas Tahun Ajaran).", 'released_at' => '2026-02-25 00:00:00'],
        // --- Daftar 1.0.3 - koneksi API terbaru (selaras dengan uwaba) ---
        ['app' => 'daftar', 'version' => '1.0.3', 'role_id' => null, 'title' => 'Koneksi API terbaru', 'changelog' => "Base URL API: getSlimApiUrl fallback ke http://localhost/api/public/api (routes terbaru, sama dengan uwaba).\nPeringatan di konsol jika VITE_API_BASE_URL tidak di-set di .env.\n.env.example: default VITE_API_BASE_URL=http://localhost/api/public/api (local), staging/production api2.alutsmani.id / api.alutsmani.id.\nversion.js: BACKEND_VERSION 2.0.0 (selaras dengan api/config.php).", 'released_at' => '2026-02-25 00:00:00'],

        // --- MyBeddian 1.0.0 – Aplikasi santri (belum ada sebelumnya, mulai versi 1) ---
        ['app' => 'mybeddian', 'version' => '1.0.0', 'role_id' => null, 'title' => 'MyBeddian 1.0.0', 'changelog' => "Aplikasi santri – pertama kali dirilis.\nLogin: verifikasi WA (nomor dari users), username & password.\nBeranda, Profil (biodata & edit), Riwayat Pembayaran.\nRiwayat: Pendaftaran, UWABA (per tahun ajaran 1447-1448), Khusus, Tunggakan.\nPembayaran iPayMu: VA, QRIS, CStore; keterangan cara bayar, download QR, hitung mundur kadaluwarsa.\nNotifikasi WA: order dibuat, pembayaran diterima, gagal, kadaluwarsa, dibatalkan (nomor users.no_wa / fallback santri).\nPWA: install ke layar utama, theme & background hitam, cegah pull-to-refresh.\nAnimasi sukses bayar: centang + hitung mundur 4 detik lalu tutup offcanvas.", 'released_at' => '2026-02-28 00:00:00'],

        // --- API 2.1.0 - Madrasah: kolom baru, pengasuh/PJGT FK users, status ---
        ['app' => 'api', 'version' => '2.1.0', 'role_id' => null, 'title' => 'API 2.1.0 – Madrasah', 'changelog' => "Tabel madrasah – kolom baru:\n• Struktural: kepala, sekretaris, bendahara\n• Kegiatan belajar: kegiatan_pagi/sore/malam (centang), kegiatan_mulai, kegiatan_sampai, tempat\n• Tingkatan: kelas_tertinggi (setelah ula–mahad ali)\n• Lain: berdiri_tahun, keterangan\n• Keterangan Lain: banin_banat, seragam, syahriah, pengelola, gedung_madrasah, kantor, bangku, kamar_mandi_murid\n• Persiapan GT: kamar_gt, kamar_mandi_gt, km_bersifat, konsumsi, kamar_gt_jarak\n• Lingkungan: masyarakat, alumni, jarak_md_lain\n• status (Pendaftar Baru, Belum Survei, Sudah Survei, Penerima, Tidak Aktif)\nPengasuh & PJGT: id_pengasuh, id_pjgt FK ke users (bukan pengurus). Response GET madrasah: pengasuh_nama/pjgt_nama = username dari users. Create/update: terima nama_pengasuh, no_pengasuh, nama_pjgt, no_pjgt dari request.\nMigrasi: 20250225000009 (madrasah kolom), 20250225000010 (pengasuh/pjgt FK users), 20250225000011 (status).", 'released_at' => '2026-02-25 12:00:00'],

        // --- API 2.2.0 - Pengurus: NIP, id AUTO_INCREMENT, reset id 1,2,3... ---
        ['app' => 'api', 'version' => '2.2.0', 'role_id' => null, 'title' => 'API 2.2.0 – Pengurus NIP & Reset ID', 'changelog' => "Pengurus – skema dan data:\n• Kolom NIP (Nomor Induk Pengurus): unik, untuk input/tampilan (daftar, koordinator, lupa password). Nilai awal diisi dari id lama.\n• id pengurus diubah menjadi AUTO_INCREMENT. Insert pengurus baru mendapat id otomatis.\n• Reset id pengurus menjadi 1, 2, 3, … (satu kali). Semua referensi FK ke pengurus.id di seluruh tabel (madrasah.id_koordinator, pengurus___role, pengeluaran, pemasukan, uwaba___bayar, uwaba___tunggakan, uwaba___bayar_tunggakan, uwaba___khusus, uwaba___bayar_khusus, payment, psb, santri___berkas, santri___boyong, whatsapp, umroh, user___aktivitas, user___setup_tokens, dll.) telah di-update ke id baru.\n• Perbaikan: tabel uwaba memakai nama lengkap (uwaba___tunggakan, uwaba___bayar_tunggakan, uwaba___khusus, uwaba___bayar_khusus). Migrasi perbaikan (20250225000014) meng-update id_admin di tabel uwaba yang terlewat.\nMigrasi: 20250225000012 (NIP + AUTO_INCREMENT), 20250225000013 (reset id + update FK), 20250225000014 (fix FK uwaba).", 'released_at' => '2026-02-25 18:00:00'],

        // --- UWABA 6.3.6 - Data Madrasah: form lengkap, status, filter, badge ---
        ['app' => 'uwaba', 'version' => '6.3.6', 'role_id' => 23, 'title' => 'UGT – Data Madrasah', 'changelog' => "Form madrasah: section Struktural (kepala, sekretaris, bendahara). Kelas tertinggi placeholder: Contoh: 3 Wustha. Keterangan label: Hal-hal yang perlu diinformasikan. Section Keterangan Lain (banin/banat, seragam, syahriah, pengelola, gedung, kantor, bangku, kamar mandi murid). Section Persiapan untuk Guru Tugas (kamar GT, kamar mandi GT, KM bersifat, konsumsi, jarak). Section Lingkungan Madrasah (masyarakat, alumni, jarak MD lain).\nPengasuh & PJGT: tampil Username dari users (read-only); input Nama dan WA tetap bisa diubah.\nStatus: field Status (Pendaftar Baru, Belum Survei, Sudah Survei, Penerima, Tidak Aktif). Kolom Status di tabel list. Filter Status di panel filter. Grid: badge status di pojok kiri atas dengan variasi warna (biru, amber, cyan, emerald, abu).\nTabel list: kolom Kepala. Export/Import/Bulk Edit mendukung semua field baru.", 'released_at' => '2026-02-25 12:00:00'],
        ['app' => 'uwaba', 'version' => '6.3.6', 'role_id' => 1, 'title' => 'UGT – Data Madrasah', 'changelog' => "Form madrasah lengkap (Struktural, Keterangan Lain, Persiapan GT, Lingkungan Madrasah). Pengasuh/PJGT tampil username; nama & WA bisa diedit. Status madrasah + filter + badge berwarna di grid. Kolom Kepala di list. Export/Import/Bulk Edit field baru.", 'released_at' => '2026-02-25 12:00:00'],

        // --- API 2.3.0 – Profil: no_wa_verified_at, satu sumber nomor ---
        ['app' => 'api', 'version' => '2.3.0', 'role_id' => null, 'title' => 'API 2.3.0 – Profil & Kontak', 'changelog' => "Profil user: response getUserById mengembalikan no_wa_verified_at (tanggal terakhir verifikasi WA). Nomor kontak pengurus satu sumber: users.no_wa (kolom no_telpon di pengurus dihapus via migrasi).\nUpdate profil: hanya field yang masih ada di tabel pengurus/users yang di-update; email di users, tanpa no_telpon/jabatan di pengurus.\nAktivitas: GET /api/v2/profil/aktivitas tetap mendukung query limit & offset (default limit 50, max 100).", 'released_at' => '2026-02-27 00:00:00'],

        // --- UWABA 6.3.7 – Profil: Kontak hanya WhatsApp, verifikasi, Aktivitas 10 terakhir ---
        ['app' => 'uwaba', 'version' => '6.3.7', 'role_id' => 1, 'title' => 'Profil & Edit Profil', 'changelog' => "Kontak: section Kontak hanya menampilkan Email dan WhatsApp (telepon dihapus). WhatsApp menampilkan badge Terverifikasi dan tanggal terakhir verifikasi (no_wa_verified_at); jika belum verifikasi tampil teks Belum verifikasi.\nEdit Profil: field Telepon dihapus; hanya WhatsApp (read-only + Ganti nomor) dengan badge verifikasi dan tanggal terakhir verifikasi.\nAktivitas saya: dibatasi 10 aktivitas terakhir di halaman profil.", 'released_at' => '2026-02-27 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.3.7', 'role_id' => null, 'title' => 'Profil', 'changelog' => "Kontak hanya WhatsApp dengan status verifikasi dan tanggal verifikasi. Aktivitas saya: 10 aktivitas terakhir.", 'released_at' => '2026-02-27 00:00:00'],

        // --- UWABA 6.3.8 – Pendaftaran: label tab, Item kategori; Manage Data: filter multi, Ket, export offcanvas; Umroh: list klik ke edit ---
        ['app' => 'uwaba', 'version' => '6.3.8', 'role_id' => 15, 'title' => 'Pendaftaran (PSB)', 'changelog' => "Tab Pendaftaran: label \"Kondisi Registrasi\" disingkat menjadi \"Registrasi\"; \"Assign Item\" menjadi \"Assign\".\nHalaman Item: field Kategori di form Buat/Edit Item berupa dropdown yang diisi dari kolom kategori tabel item (nilai unik).", 'released_at' => '2026-02-27 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.3.8', 'role_id' => 16, 'title' => 'Pendaftaran (PSB)', 'changelog' => "Tab: Registrasi, Assign. Item: dropdown Kategori dari nilai unik tabel item.", 'released_at' => '2026-02-27 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.3.8', 'role_id' => 2, 'title' => 'Pembayaran (UWABA)', 'changelog' => "Manage Data: semua filter (Status, Kategori, Count, Ket, Diniyah, Formal, LTTQ, dll.) dapat memilih banyak opsi (checkbox). Kolom Ket (Lunas/Kurang/Belum) berdasarkan pembayaran UWABA tahun ajaran aktif. Filter Ket. Tombol Export membuka offcanvas kanan: pilih kolom yang mau dieksport lalu Eksport ke Excel; pilihan kolom disimpan di localStorage.", 'released_at' => '2026-02-27 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.3.8', 'role_id' => 4, 'title' => 'Pembayaran (UWABA)', 'changelog' => "Manage Data: filter multi-select (checkbox), kolom Ket, filter Ket, export via offcanvas pilih kolom.", 'released_at' => '2026-02-27 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.3.8', 'role_id' => 8, 'title' => 'Umroh', 'changelog' => "List Jamaah: tombol Detail dan Edit dihapus. Klik baris list langsung membuka halaman edit jamaah.", 'released_at' => '2026-02-27 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.3.8', 'role_id' => 9, 'title' => 'Umroh', 'changelog' => "List Jamaah: klik baris langsung ke halaman edit; tombol Detail/Edit dihapus.", 'released_at' => '2026-02-27 00:00:00'],

        // --- UWABA 6.3.9 – Beranda: tahun ajaran Masehi, kotak tanggal HP, menu berwarna, selamat datang gradien, aktivitas rapi ---
        ['app' => 'uwaba', 'version' => '6.3.9', 'role_id' => null, 'title' => 'Beranda & Tampilan', 'changelog' => "Tahun ajaran: tampil Hijriyah dan Masehi (contoh: 1446-1447 / 2025-2026) di semua tempat tahun ajaran di Beranda.\nHP – Kotak tanggal: margin samping (mx-4); tampilan tiga kotak terpisah seperti Ringkasan Keuangan (Tanggal, Hari & Jam, Tahun Ajaran) dengan warna slate, teal, amber.\nMenu Beranda: kotak menu diperkecil; tiap menu punya warna (teal, emerald, blue, violet, amber, rose, cyan, indigo, orange, pink); background kartu disamakan dengan background icon.\nKotak selamat datang (HP): gradien transparan ke bawah (atas solid, bawah 100% transparan); mode terang tanpa border dan shadow di mobile; transparansi dipertegas di mode terang.\nAktivitas Terbaru: tampilan diperbaiki – list rapi dengan pemisah antar item, tanggal di baris kedua; tombol Lihat Semua jika user punya akses menu Aktivitas.", 'released_at' => '2026-02-28 00:00:00'],

        // --- UWABA 6.4.0 – Halaman Aktivitas Saya, Beranda tahun ajaran & layout, Header dropdown TA, Semua Menu, Profil disederhanakan ---
        ['app' => 'uwaba', 'version' => '6.4.0', 'role_id' => null, 'title' => 'Halaman & Menu Baru', 'changelog' => "Halaman Aktivitas Saya (/aktivitas-saya): halaman baru untuk aktivitas user (audit log) dengan list dan pagination (Muat lebih banyak). Kotak Aktivitas Login (perangkat) dipindah dari Profil ke halaman ini – daftar session, offcanvas detail perangkat, modal konfirmasi log out/keluar perangkat lain. Menu Sidebar dan navMenuConfig: item Aktivitas Saya (semua user). Tombol Lihat Semua di Beranda (Aktivitas Terbaru) mengarah ke /aktivitas-saya.", 'released_at' => '2026-02-28 12:00:00'],
        ['app' => 'uwaba', 'version' => '6.4.0', 'role_id' => null, 'title' => 'Beranda – Tahun Ajaran & Layout', 'changelog' => "Tahun ajaran: di HP dan PC pindah ke bawah nama, berjajar horizontal (select Hijriyah / Masehi), tanpa border dan tanpa background, bisa diubah (sinkron dengan store/header).\nKotak 2 (HP): hanya Tanggal dan Hari & Jam (dua kolom); tahun ajaran hanya di kotak 1.\nPC (md ke atas): blok Tanggal & Hari & Jam pindah ke kanan selamat datang & nama (kolom kanan dengan border kiri).\nTablet (sm): tampilan tetap – Tanggal & Hari & Jam di bawah nama. Breakpoint: tablet sm (640px), PC md (768px).", 'released_at' => '2026-02-28 12:00:00'],
        ['app' => 'uwaba', 'version' => '6.4.0', 'role_id' => null, 'title' => 'Header & Profil', 'changelog' => "Header: select tahun ajaran (desktop) tanpa background dan border, teks rata tengah, panah tetap. Custom dropdown tahun ajaran (desktop): saat terbuka tampil panel modern (rounded, shadow, animasi), opsi terpilih dengan aksen teal. Judul halaman Aktivitas Saya di header.\nProfil: kotak Aktivitas saya (audit log) dan kotak Aktivitas login (perangkat) dihapus – konten pindah ke halaman Aktivitas Saya.", 'released_at' => '2026-02-28 12:00:00'],
        ['app' => 'uwaba', 'version' => '6.4.0', 'role_id' => null, 'title' => 'Semua Menu & Aktivitas Saya', 'changelog' => "Semua Menu: menu item berwarna seperti di Beranda (teal, emerald, blue, violet, amber, rose, cyan, indigo, orange, pink). Kotak pembungkus per grup (border, bg halus); item tanpa bg/border. Judul Semua Menu rata tengah, lebih rapi. Menu item rata top (justify-start) agar label dua baris tidak menggeser ikon. Animasi saat load dan saat scroll (viewport root = elemen scroll, whileInView).\nAktivitas Saya: tanpa judul/subjudul duplikat di halaman; konten dibungkus elemen scroll.", 'released_at' => '2026-02-28 12:00:00'],

        // --- API 2.4.0 – getDataSantri: id_daerah di response ---
        ['app' => 'api', 'version' => '2.4.0', 'role_id' => null, 'title' => 'API 2.4.0 – Data Santri', 'changelog' => "getDataSantri: response menambah id_daerah (integer) selain id_kamar, daerah, kamar. Format konsisten: id_diniyah, id_formal, id_daerah, id_kamar untuk ubah data; diniyah, formal, daerah, kamar = nama (dari JOIN lembaga/daerah) untuk tampilan dan export.", 'released_at' => '2026-03-03 00:00:00'],

        // --- UWABA 6.4.1 – Format terbaru daerah, kamar, diniyah, formal (konsisten); Data Ijin: filter, edit, export ---
        ['app' => 'uwaba', 'version' => '6.4.1', 'role_id' => null, 'title' => 'Format Daerah, Kamar, Diniyah, Formal', 'changelog' => "Konsistensi data: Backend getDataSantri/getDataKhusus/getDataTunggakan mengembalikan id_diniyah, id_formal, id_daerah, id_kamar (untuk ubah) serta nama diniyah, formal, daerah, kamar (untuk tampilan). Semua halaman yang mengubah data santri (Bulk Edit, form edit) mengirim id_diniyah, id_formal, id_kamar ke API. Tampilan tabel, filter opsi, dan export memakai nama.", 'released_at' => '2026-03-03 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.4.1', 'role_id' => 18, 'title' => 'Data Ijin', 'changelog' => "Filter: Diniyah dan Formal memakai id (dropdown nilai = id, label = nama lembaga). Daerah dan Kamar filter tetap by nama. Tabel dan export: kolom Daerah, Kamar, Diniyah, Formal menampilkan nama dari API.\nUbah masal (Bulk Edit): kolom Diniyah/Formal pakai opsi rombel (id_diniyah, id_formal). Kolom Daerah-Kamar: pilih Daerah lalu Kamar, kirim id_kamar.\nEdit cepat (offcanvas): form edit santri seperti biodata UWABA – dropdown Daerah → Kamar (id_daerah, id_kamar), dropdown Diniyah/Formal (rombel, id_diniyah, id_formal), Gender dan Status Santri dropdown. Simpan kirim id_diniyah, id_formal, id_kamar.\nExport: tombol Export membuka offcanvas kanan untuk pilih kolom yang akan dieksport (seperti Manage Data UWABA); pilihan kolom disimpan di localStorage. Data export memakai nama daerah, kamar, diniyah, formal.", 'released_at' => '2026-03-03 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.4.1', 'role_id' => 19, 'title' => 'Data Ijin', 'changelog' => "Filter diniyah/formal by id; ubah masal pakai rombel dan id_kamar; offcanvas edit santri dengan dropdown daerah-kamar dan diniyah/formal; export via offcanvas pilih kolom.", 'released_at' => '2026-03-03 00:00:00'],

        // --- API 2.5.0 – Notifikasi & WatZap ---
        ['app' => 'api', 'version' => '2.5.0', 'role_id' => null, 'title' => 'API 2.5.0 – Notifikasi & WatZap', 'changelog' => "Pengaturan notifikasi WA (super_admin only):\n• Tabel app___settings (key-value): notification_provider (wa_sendiri | watzap). Migrasi 20260315000001.\n• GET/PUT /api/settings/notification-config: baca/simpan provider notifikasi.\nIntegrasi WatZap (api.watzap.id):\n• Config: WATZAP_API_URL, WATZAP_API_KEY, WATZAP_NUMBER_KEY (default ALL). Body kirim: api_key, number_key, phone_no, message (tanpa device_id).\n• WatzapService: proxy ke WatZap; sendMessage(phone, message, numberKey).\n• GET /api/watzap/status, GET /api/watzap/devices, POST /api/watzap/send (body: phone, message [, number_key ]). Semua endpoint watzap hanya super_admin.\nWhatsAppService:\n• getNotificationProvider(): baca dari app___settings. Jika provider = watzap → kirim lewat WatzapService (number_key ALL atau dari env); else kirim lewat WA server (WA_API_URL).\n• Semua notifikasi teks (daftar, PSB, pembayaran, auth, pengeluaran, chat) ikut setting: WA server sendiri atau WatZap.", 'released_at' => '2026-03-15 00:00:00'],

        // --- UWABA 6.4.2 – Setting Notifikasi & WatZap (super_admin) ---
        ['app' => 'uwaba', 'version' => '6.4.2', 'role_id' => 1, 'title' => 'Setting – Notifikasi & WatZap', 'changelog' => "Notifikasi (Setting → Notifikasi, hanya Super Admin):\n• Pilih provider notifikasi WA: WA server sendiri (koneksi di halaman WhatsApp, scan QR) atau WatZap (api.watzap.id).\n• Simpan dipakai seluruh aplikasi & API: daftar, PSB, pembayaran, auth, pengeluaran, chat mengikuti provider yang dipilih.\nWatZap (Setting → WatZap, hanya Super Admin):\n• Halaman kelola WatZap: tampil status konfigurasi backend (api_url, number_key).\n• Tes kirim pesan: nomor tujuan + isi pesan; optional number_key. Backend proxy ke WatZap (api_key + number_key ALL).\n• Link dokumentasi: API WatZap, menambahkan nomor WA untuk API.\nMenu: Notifikasi dan WatZap ditambah di grup Setting (menuConfig), requiresSuperAdmin: true. Route /settings/notifikasi, /settings/watzap dilindungi SuperAdminRoute.", 'released_at' => '2026-03-15 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.4.2', 'role_id' => null, 'title' => 'Notifikasi & WatZap', 'changelog' => "Setting → Notifikasi: pilih WA server sendiri atau WatZap (hanya Super Admin). Semua notifikasi WA (daftar, pembayaran, dll.) ikut setting.\nSetting → WatZap: status & tes kirim pesan lewat WatZap (hanya Super Admin).", 'released_at' => '2026-03-15 00:00:00'],

        // --- UWABA 6.5.6 (eBeddien) – Auth, Kalender offcanvas, Tema, Token 5 jam, Animasi flip ---
        ['app' => 'uwaba', 'version' => '6.5.6', 'role_id' => null, 'title' => 'Login, Token & Kalender', 'changelog' => "Token login: batas 5 jam dari terakhir digunakan (sliding). Lewat 5 jam wajib login lagi. Refresh token tetap disimpan (tanpa auto-login ke aplikasi).\nKalender (HP): tombol kalender di bawah layar (icon + label kecil, tanpa BG). Klik membuka offcanvas dari bawah dengan kepala bergelombang (animasi air), tombol tutup panah ke bawah. Kalender bisa diakses bagi yang pernah login (auth_ever_logged_in/refresh_token tetap).\nKalender (PC): offcanvas dari kiri; header dengan judul dan tombol X. Klik ikon kalender di strip pemisah membuka panel kalender dari kiri.", 'released_at' => '2026-03-17 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.5.6', 'role_id' => null, 'title' => 'Tema & Tombol Pemisah', 'changelog' => "Tema gelap/terang: icon tema dengan animasi flip saat ganti tema (desktop dan mobile).\nMode PC: tombol tema dan kalender dipindah ke garis vertikal pemisah kiri/kanan; icon tersusun vertikal dengan background bulat sesuai tema (putih/gelap).\nMode HP: tombol tema dan kalender di bawah, berjejer, style sama (icon + label kecil, tanpa BG).", 'released_at' => '2026-03-17 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.5.6', 'role_id' => null, 'title' => 'Animasi Halaman Auth', 'changelog' => "Login, Daftar, Lupa Password: saat ganti tema – logo flip ke kanan (AnimatePresence); input flip dengan scale (animasi flip-scale-2-hor-bottom). Satu wrapper untuk semua input agar animasi konsisten; kelas idle mereset transform agar animasi jalan tiap kali ganti tema; backface-visibility menghindari teks terbalik.", 'released_at' => '2026-03-17 00:00:00'],
    ];

    public function run(): void
    {
        $seen = [];
        foreach ($this->entries as $row) {
            $key = $row['app'] . '|' . $row['version'];
            if (!isset($seen[$key])) {
                $seen[$key] = true;
                $this->execute(sprintf(
                    "DELETE FROM app_version_changelog WHERE app = %s AND version = %s",
                    $this->getAdapter()->getConnection()->quote($row['app']),
                    $this->getAdapter()->getConnection()->quote($row['version'])
                ));
            }
        }
        $table = $this->table('app_version_changelog');
        $table->insert($this->entries);
        $table->saveData();
    }
}
