<?php

declare(strict_types=1);

use Phinx\Seed\AbstractSeed;

/**
 * Seed: isi app_version_changelog (versi aplikasi + changelog per role).
 *
 * CARA INSERT DATA CHANGELOG (tidak perlu buat file PHP baru):
 * 1. Buka file ini (ChangelogVersionSeed.php)
 * 2. Tambah baris baru di array $entries di bawah — format: app, version, role_id, title, changelog, released_at
 * 3. Simpan, lalu jalankan: php vendor/bin/phinx seed:run -s ChangelogVersionSeed
 *
 * Seed akan hapus dulu entri yang app+version sama, lalu insert semua (termasuk yang baru).
 * role_id: NULL = visible semua (public). role_id = id dari tabel role (1=super_admin, 2=admin_uwaba, ...).
 */
class ChangelogVersionSeed extends AbstractSeed
{
    /** Daftar entri changelog. Untuk rilis baru (mis. uwaba 6.2.3): tambah baris di sini, jangan buat file baru. */
    private array $entries = [
        // --- Backend (API) 1.0.0 - ringkasan ---
        ['app' => 'api', 'version' => '1.0.0', 'role_id' => null, 'title' => 'Backend API', 'changelog' => "Slim 4, PHP 7.4+\nAuth JWT, CORS, rate limit\nMigrasi & seed via Phinx (schema + RoleSeed, ChangelogVersionSeed)\nEndpoint GET /api/version (versi backend)\nEndpoint GET /api/version/changelog (changelog per app & role)\nPengaturan, Kalender, Hari Penting\nUWABA, Pembayaran, Santri, Users, Lembaga, Jabatan\nPSB, Pengeluaran, Pemasukan, Umroh, Ijin, Juara, WhatsApp, UGT", 'released_at' => '2026-02-24 00:00:00'],
        // --- Backend (API) 2.0.0 - routes migration, CORS, fix login 500 ---
        ['app' => 'api', 'version' => '2.0.0', 'role_id' => null, 'title' => 'Backend API 2.0.0', 'changelog' => "Migrasi routes: definisi route dipindah dari index.php ke api/routes/*.php (21 file). API v1 path tidak berubah.\nPreflight OPTIONS: penanganan awal di index.php + perbaikan CorsMiddleware agar login dari localhost:5173 tidak kena CORS.\nRoute files: tambah use statement untuk middleware & controller (perbaikan Class not found saat registrasi route).\nLogin v2: catch Throwable dan tampilkan pesan error di response (development) agar 500 mudah dilacak.\nFrontend: fallback base URL api/public/api (uwaba & daftar), .env.example & env.production (APP_ENV, APP_URL).\nDokumen: PLAN_ROUTES_MIGRATION.md (verifikasi), phinx.php (contoh migrate -e development).", 'released_at' => '2026-02-25 00:00:00'],
        // --- UWABA 6.2.2 (contoh dari seed_uwaba_6.2.2.sql) ---
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => 15, 'title' => 'Pendaftaran (PSB)', 'changelog' => "Dashboard Pendaftaran\nData Pendaftar\nPadukan Data\nPengaturan PSB\nItem & Manage Item Set\nManage Kondisi & Kondisi Registrasi\nAssign Item ke Set\nSimulasi\nImage Editor (crop/upload)", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => 16, 'title' => 'Pendaftaran (PSB)', 'changelog' => "Dashboard Pendaftaran\nData Pendaftar\nPadukan Data\nPengaturan PSB\nItem & Manage Item Set\nManage Kondisi & Kondisi Registrasi\nAssign Item ke Set\nSimulasi\nImage Editor (crop/upload)", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => 2, 'title' => 'Pembayaran (UWABA)', 'changelog' => "Dashboard Pembayaran\nInput pembayaran syahriah (UWABA)\nTunggakan\nKhusus\nManage Data pembayaran\nLaporan pembayaran\nImport Khusus & Import Tunggakan\nPrint kwitansi", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => 4, 'title' => 'Pembayaran (UWABA)', 'changelog' => "Dashboard Pembayaran\nInput pembayaran syahriah (UWABA)\nTunggakan\nKhusus\nManage Data pembayaran\nLaporan pembayaran\nImport Khusus & Import Tunggakan\nPrint kwitansi", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => null, 'title' => 'Keuangan', 'changelog' => "Dashboard Keuangan\nPengeluaran & Rencana Pengeluaran\nPemasukan\nAktivitas & Aktivitas Tahun Ajaran", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => 8, 'title' => 'Umroh', 'changelog' => "Dashboard Umroh\nJamaah Umroh\nTabungan Umroh\nLaporan Umroh", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => 9, 'title' => 'Umroh', 'changelog' => "Dashboard Umroh\nJamaah Umroh\nTabungan Umroh\nLaporan Umroh", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => 18, 'title' => 'Ijin & Juara', 'changelog' => "Dashboard Ijin\nData Ijin\nData Boyong\nData Juara", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => 19, 'title' => 'Ijin & Juara', 'changelog' => "Dashboard Ijin\nData Ijin\nData Boyong\nData Juara", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => 22, 'title' => 'Kalender', 'changelog' => "Kalender (Hijriah/Masehi)\nHari Penting\nPengaturan Kalender\nConverter tanggal", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => 1, 'title' => 'Pengaturan & User', 'changelog' => "Dashboard Umum\nManage Users & Edit User\nImport Users\nPengurus\nLembaga\nManage Jabatan\nManage Uploads\nProfil (lihat & edit)", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => null, 'title' => 'Akses Santri (Public)', 'changelog' => "Tampilan public untuk santri: Santri, UWABA, Khusus, Tunggakan, Ijin, Shohifah, Kalender (tanpa login)", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => 23, 'title' => 'UGT & Lainnya', 'changelog' => "Data Madrasah (UGT)\nLogin & role-based access\nSetup Akun / Ubah Password / Ubah Username (link dari WA)\nPWA & notifikasi push\nHeader staging (merah)", 'released_at' => '2025-02-24 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.2.2', 'role_id' => 1, 'title' => 'UGT & Lainnya', 'changelog' => "Data Madrasah (UGT)\nLogin & role-based access\nSetup Akun / Ubah Password / Ubah Username (link dari WA)\nPWA & notifikasi push\nHeader staging (merah)", 'released_at' => '2025-02-24 00:00:00'],
        // --- UWABA 6.3.5 - koneksi API, menu Koordinator, UGT, Setting ---
        ['app' => 'uwaba', 'version' => '6.3.5', 'role_id' => null, 'title' => 'Koneksi API & Login', 'changelog' => "Base URL API: fallback ke http://localhost/api/public/api (routes terbaru). .env.example: VITE_API_BASE_URL untuk local (api/public/api).\nPerbaikan CORS: preflight OPTIONS di backend agar login dari localhost:5173 tidak diblokir.\nVersi backend (BACKEND_VERSION): 2.0.0.", 'released_at' => '2026-02-25 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.3.5', 'role_id' => 23, 'title' => 'UGT: Koordinator & Data Madrasah', 'changelog' => "Menu Koordinator (admin_ugt, super_admin): halaman Kelola Koordinator, daftar pengurus dengan role koordinator, filter by role/lembaga/jabatan/status, tambah role koordinator, nonaktifkan (hapus) role koordinator.\nData Madrasah: filter koordinator, field ID Koordinator di form tambah/edit madrasah, Cari Koordinator offcanvas, koordinator terkunci untuk role koordinator_ugt (hanya lihat data sendiri).\nImport/Export madrasah: kolom koordinator, bulk edit ID Koordinator.", 'released_at' => '2026-02-25 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.3.5', 'role_id' => 1, 'title' => 'UGT & Setting', 'changelog' => "UGT: Menu Koordinator, Data Madrasah dengan filter koordinator dan assign koordinator ke madrasah.\nSetting: menu Role & Akses, Fitur (navMenuConfig).\nKeuangan: menu Aktivitas TA (Aktivitas Tahun Ajaran).", 'released_at' => '2026-02-25 00:00:00'],
        // --- Daftar 1.0.3 - koneksi API terbaru (selaras dengan uwaba) ---
        ['app' => 'daftar', 'version' => '1.0.3', 'role_id' => null, 'title' => 'Koneksi API terbaru', 'changelog' => "Base URL API: getSlimApiUrl fallback ke http://localhost/api/public/api (routes terbaru, sama dengan uwaba).\nPeringatan di konsol jika VITE_API_BASE_URL tidak di-set di .env.\n.env.example: default VITE_API_BASE_URL=http://localhost/api/public/api (local), staging/production api2.alutsmani.id / api.alutsmani.id.\nversion.js: BACKEND_VERSION 2.0.0 (selaras dengan api/config.php).", 'released_at' => '2026-02-25 00:00:00'],

        // --- MyBeddian 1.0.0 – Aplikasi santri (belum ada sebelumnya, mulai versi 1) ---
        ['app' => 'mybeddian', 'version' => '1.0.0', 'role_id' => null, 'title' => 'MyBeddian 1.0.0', 'changelog' => "Aplikasi santri – pertama kali dirilis.\nLogin: verifikasi WA (nomor dari users), username & password.\nBeranda, Profil (biodata & edit), Riwayat Pembayaran.\nRiwayat: Pendaftaran, UWABA (per tahun ajaran 1447-1448), Khusus, Tunggakan.\nPembayaran iPayMu: VA, QRIS, CStore; keterangan cara bayar, download QR, hitung mundur kadaluwarsa.\nNotifikasi WA: order dibuat, pembayaran diterima, gagal, kadaluwarsa, dibatalkan (nomor users.no_wa / fallback santri).\nPWA: install ke layar utama, theme & background hitam, cegah pull-to-refresh.\nAnimasi sukses bayar: centang + hitung mundur 4 detik lalu tutup offcanvas.", 'released_at' => '2026-02-28 00:00:00'],

        // --- API 2.1.0 - Madrasah: kolom baru, pengasuh/PJGT FK users, status ---
        ['app' => 'api', 'version' => '2.1.0', 'role_id' => null, 'title' => 'API 2.1.0 – Madrasah', 'changelog' => "Tabel madrasah – kolom baru:\n• Struktural: kepala, sekretaris, bendahara\n• Kegiatan belajar: kegiatan_pagi/sore/malam (centang), kegiatan_mulai, kegiatan_sampai, tempat\n• Tingkatan: kelas_tertinggi (setelah ula–mahad ali)\n• Lain: berdiri_tahun, keterangan\n• Keterangan Lain: banin_banat, seragam, syahriah, pengelola, gedung_madrasah, kantor, bangku, kamar_mandi_murid\n• Persiapan GT: kamar_gt, kamar_mandi_gt, km_bersifat, konsumsi, kamar_gt_jarak\n• Lingkungan: masyarakat, alumni, jarak_md_lain\n• status (Pendaftar Baru, Belum Survei, Sudah Survei, Penerima, Tidak Aktif)\nPengasuh & PJGT: id_pengasuh, id_pjgt FK ke users (bukan pengurus). Response GET madrasah: pengasuh_nama/pjgt_nama = username dari users. Create/update: terima nama_pengasuh, no_pengasuh, nama_pjgt, no_pjgt dari request.\nMigrasi: 20250225000009 (madrasah kolom), 20250225000010 (pengasuh/pjgt FK users), 20250225000011 (status).", 'released_at' => '2026-02-25 12:00:00'],

        // --- API 2.2.0 - Pengurus: NIP, id AUTO_INCREMENT, reset id 1,2,3... ---
        ['app' => 'api', 'version' => '2.2.0', 'role_id' => null, 'title' => 'API 2.2.0 – Pengurus NIP & Reset ID', 'changelog' => "Pengurus – skema dan data:\n• Kolom NIP (Nomor Induk Pengurus): unik, untuk input/tampilan (daftar, koordinator, lupa password). Nilai awal diisi dari id lama.\n• id pengurus diubah menjadi AUTO_INCREMENT. Insert pengurus baru mendapat id otomatis.\n• Reset id pengurus menjadi 1, 2, 3, … (satu kali). Semua referensi FK ke pengurus.id di seluruh tabel (madrasah.id_koordinator, pengurus___role, pengeluaran, pemasukan, uwaba___bayar, uwaba___tunggakan, uwaba___bayar_tunggakan, uwaba___khusus, uwaba___bayar_khusus, payment, psb, santri___berkas, santri___boyong, whatsapp, umroh, user___aktivitas, user___setup_tokens, dll.) telah di-update ke id baru.\n• Perbaikan: tabel uwaba memakai nama lengkap (uwaba___tunggakan, uwaba___bayar_tunggakan, uwaba___khusus, uwaba___bayar_khusus). Migrasi perbaikan (20250225000014) meng-update id_admin di tabel uwaba yang terlewat.\nMigrasi: 20250225000012 (NIP + AUTO_INCREMENT), 20250225000013 (reset id + update FK), 20250225000014 (fix FK uwaba).", 'released_at' => '2026-02-25 18:00:00'],

        // --- UWABA 6.3.6 - Data Madrasah: form lengkap, status, filter, badge ---
        ['app' => 'uwaba', 'version' => '6.3.6', 'role_id' => 23, 'title' => 'UGT – Data Madrasah', 'changelog' => "Form madrasah: section Struktural (kepala, sekretaris, bendahara). Kelas tertinggi placeholder: Contoh: 3 Wustha. Keterangan label: Hal-hal yang perlu diinformasikan. Section Keterangan Lain (banin/banat, seragam, syahriah, pengelola, gedung, kantor, bangku, kamar mandi murid). Section Persiapan untuk Guru Tugas (kamar GT, kamar mandi GT, KM bersifat, konsumsi, jarak). Section Lingkungan Madrasah (masyarakat, alumni, jarak MD lain).\nPengasuh & PJGT: tampil Username dari users (read-only); input Nama dan WA tetap bisa diubah.\nStatus: field Status (Pendaftar Baru, Belum Survei, Sudah Survei, Penerima, Tidak Aktif). Kolom Status di tabel list. Filter Status di panel filter. Grid: badge status di pojok kiri atas dengan variasi warna (biru, amber, cyan, emerald, abu).\nTabel list: kolom Kepala. Export/Import/Bulk Edit mendukung semua field baru.", 'released_at' => '2026-02-25 12:00:00'],
        ['app' => 'uwaba', 'version' => '6.3.6', 'role_id' => 1, 'title' => 'UGT – Data Madrasah', 'changelog' => "Form madrasah lengkap (Struktural, Keterangan Lain, Persiapan GT, Lingkungan Madrasah). Pengasuh/PJGT tampil username; nama & WA bisa diedit. Status madrasah + filter + badge berwarna di grid. Kolom Kepala di list. Export/Import/Bulk Edit field baru.", 'released_at' => '2026-02-25 12:00:00'],

        // --- API 2.3.0 – Profil: no_wa_verified_at, satu sumber nomor ---
        ['app' => 'api', 'version' => '2.3.0', 'role_id' => null, 'title' => 'API 2.3.0 – Profil & Kontak', 'changelog' => "Profil user: response getUserById mengembalikan no_wa_verified_at (tanggal terakhir verifikasi WA). Nomor kontak pengurus satu sumber: users.no_wa (kolom no_telpon di pengurus dihapus via migrasi).\nUpdate profil: hanya field yang masih ada di tabel pengurus/users yang di-update; email di users, tanpa no_telpon/jabatan di pengurus.\nAktivitas: GET /api/v2/profil/aktivitas tetap mendukung query limit & offset (default limit 50, max 100).", 'released_at' => '2026-02-27 00:00:00'],

        // --- UWABA 6.3.7 – Profil: Kontak hanya WhatsApp, verifikasi, Aktivitas 10 terakhir ---
        ['app' => 'uwaba', 'version' => '6.3.7', 'role_id' => 1, 'title' => 'Profil & Edit Profil', 'changelog' => "Kontak: section Kontak hanya menampilkan Email dan WhatsApp (telepon dihapus). WhatsApp menampilkan badge Terverifikasi dan tanggal terakhir verifikasi (no_wa_verified_at); jika belum verifikasi tampil teks Belum verifikasi.\nEdit Profil: field Telepon dihapus; hanya WhatsApp (read-only + Ganti nomor) dengan badge verifikasi dan tanggal terakhir verifikasi.\nAktivitas saya: dibatasi 10 aktivitas terakhir di halaman profil.", 'released_at' => '2026-02-27 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.3.7', 'role_id' => null, 'title' => 'Profil', 'changelog' => "Kontak hanya WhatsApp dengan status verifikasi dan tanggal verifikasi. Aktivitas saya: 10 aktivitas terakhir.", 'released_at' => '2026-02-27 00:00:00'],

        // --- UWABA 6.3.8 – Pendaftaran: label tab, Item kategori; Manage Data: filter multi, Ket, export offcanvas; Umroh: list klik ke edit ---
        ['app' => 'uwaba', 'version' => '6.3.8', 'role_id' => 15, 'title' => 'Pendaftaran (PSB)', 'changelog' => "Tab Pendaftaran: label \"Kondisi Registrasi\" disingkat menjadi \"Registrasi\"; \"Assign Item\" menjadi \"Assign\".\nHalaman Item: field Kategori di form Buat/Edit Item berupa dropdown yang diisi dari kolom kategori tabel item (nilai unik).", 'released_at' => '2026-02-27 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.3.8', 'role_id' => 16, 'title' => 'Pendaftaran (PSB)', 'changelog' => "Tab: Registrasi, Assign. Item: dropdown Kategori dari nilai unik tabel item.", 'released_at' => '2026-02-27 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.3.8', 'role_id' => 2, 'title' => 'Pembayaran (UWABA)', 'changelog' => "Manage Data: semua filter (Status, Kategori, Count, Ket, Diniyah, Formal, LTTQ, dll.) dapat memilih banyak opsi (checkbox). Kolom Ket (Lunas/Kurang/Belum) berdasarkan pembayaran UWABA tahun ajaran aktif. Filter Ket. Tombol Export membuka offcanvas kanan: pilih kolom yang mau dieksport lalu Eksport ke Excel; pilihan kolom disimpan di localStorage.", 'released_at' => '2026-02-27 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.3.8', 'role_id' => 4, 'title' => 'Pembayaran (UWABA)', 'changelog' => "Manage Data: filter multi-select (checkbox), kolom Ket, filter Ket, export via offcanvas pilih kolom.", 'released_at' => '2026-02-27 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.3.8', 'role_id' => 8, 'title' => 'Umroh', 'changelog' => "List Jamaah: tombol Detail dan Edit dihapus. Klik baris list langsung membuka halaman edit jamaah.", 'released_at' => '2026-02-27 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.3.8', 'role_id' => 9, 'title' => 'Umroh', 'changelog' => "List Jamaah: klik baris langsung ke halaman edit; tombol Detail/Edit dihapus.", 'released_at' => '2026-02-27 00:00:00'],

        // --- UWABA 6.3.9 – Beranda: tahun ajaran Masehi, kotak tanggal HP, menu berwarna, selamat datang gradien, aktivitas rapi ---
        ['app' => 'uwaba', 'version' => '6.3.9', 'role_id' => null, 'title' => 'Beranda & Tampilan', 'changelog' => "Tahun ajaran: tampil Hijriyah dan Masehi (contoh: 1446-1447 / 2025-2026) di semua tempat tahun ajaran di Beranda.\nHP – Kotak tanggal: margin samping (mx-4); tampilan tiga kotak terpisah seperti Ringkasan Keuangan (Tanggal, Hari & Jam, Tahun Ajaran) dengan warna slate, teal, amber.\nMenu Beranda: kotak menu diperkecil; tiap menu punya warna (teal, emerald, blue, violet, amber, rose, cyan, indigo, orange, pink); background kartu disamakan dengan background icon.\nKotak selamat datang (HP): gradien transparan ke bawah (atas solid, bawah 100% transparan); mode terang tanpa border dan shadow di mobile; transparansi dipertegas di mode terang.\nAktivitas Terbaru: tampilan diperbaiki – list rapi dengan pemisah antar item, tanggal di baris kedua; tombol Lihat Semua jika user punya akses menu Aktivitas.", 'released_at' => '2026-02-28 00:00:00'],

        // --- UWABA 6.4.0 – Halaman Aktivitas Saya, Beranda tahun ajaran & layout, Header dropdown TA, Semua Menu, Profil disederhanakan ---
        ['app' => 'uwaba', 'version' => '6.4.0', 'role_id' => null, 'title' => 'Halaman & Menu Baru', 'changelog' => "Halaman Aktivitas Saya (/aktivitas-saya): halaman baru untuk aktivitas user (audit log) dengan list dan pagination (Muat lebih banyak). Kotak Aktivitas Login (perangkat) dipindah dari Profil ke halaman ini – daftar session, offcanvas detail perangkat, modal konfirmasi log out/keluar perangkat lain. Menu Sidebar dan navMenuConfig: item Aktivitas Saya (semua user). Tombol Lihat Semua di Beranda (Aktivitas Terbaru) mengarah ke /aktivitas-saya.", 'released_at' => '2026-02-28 12:00:00'],
        ['app' => 'uwaba', 'version' => '6.4.0', 'role_id' => null, 'title' => 'Beranda – Tahun Ajaran & Layout', 'changelog' => "Tahun ajaran: di HP dan PC pindah ke bawah nama, berjajar horizontal (select Hijriyah / Masehi), tanpa border dan tanpa background, bisa diubah (sinkron dengan store/header).\nKotak 2 (HP): hanya Tanggal dan Hari & Jam (dua kolom); tahun ajaran hanya di kotak 1.\nPC (md ke atas): blok Tanggal & Hari & Jam pindah ke kanan selamat datang & nama (kolom kanan dengan border kiri).\nTablet (sm): tampilan tetap – Tanggal & Hari & Jam di bawah nama. Breakpoint: tablet sm (640px), PC md (768px).", 'released_at' => '2026-02-28 12:00:00'],
        ['app' => 'uwaba', 'version' => '6.4.0', 'role_id' => null, 'title' => 'Header & Profil', 'changelog' => "Header: select tahun ajaran (desktop) tanpa background dan border, teks rata tengah, panah tetap. Custom dropdown tahun ajaran (desktop): saat terbuka tampil panel modern (rounded, shadow, animasi), opsi terpilih dengan aksen teal. Judul halaman Aktivitas Saya di header.\nProfil: kotak Aktivitas saya (audit log) dan kotak Aktivitas login (perangkat) dihapus – konten pindah ke halaman Aktivitas Saya.", 'released_at' => '2026-02-28 12:00:00'],
        ['app' => 'uwaba', 'version' => '6.4.0', 'role_id' => null, 'title' => 'Semua Menu & Aktivitas Saya', 'changelog' => "Semua Menu: menu item berwarna seperti di Beranda (teal, emerald, blue, violet, amber, rose, cyan, indigo, orange, pink). Kotak pembungkus per grup (border, bg halus); item tanpa bg/border. Judul Semua Menu rata tengah, lebih rapi. Menu item rata top (justify-start) agar label dua baris tidak menggeser ikon. Animasi saat load dan saat scroll (viewport root = elemen scroll, whileInView).\nAktivitas Saya: tanpa judul/subjudul duplikat di halaman; konten dibungkus elemen scroll.", 'released_at' => '2026-02-28 12:00:00'],

        // --- API 2.4.0 – getDataSantri: id_daerah di response ---
        ['app' => 'api', 'version' => '2.4.0', 'role_id' => null, 'title' => 'API 2.4.0 – Data Santri', 'changelog' => "getDataSantri: response menambah id_daerah (integer) selain id_kamar, daerah, kamar. Format konsisten: id_diniyah, id_formal, id_daerah, id_kamar untuk ubah data; diniyah, formal, daerah, kamar = nama (dari JOIN lembaga/daerah) untuk tampilan dan export.", 'released_at' => '2026-03-03 00:00:00'],

        // --- UWABA 6.4.1 – Format terbaru daerah, kamar, diniyah, formal (konsisten); Data Ijin: filter, edit, export ---
        ['app' => 'uwaba', 'version' => '6.4.1', 'role_id' => null, 'title' => 'Format Daerah, Kamar, Diniyah, Formal', 'changelog' => "Konsistensi data: Backend getDataSantri/getDataKhusus/getDataTunggakan mengembalikan id_diniyah, id_formal, id_daerah, id_kamar (untuk ubah) serta nama diniyah, formal, daerah, kamar (untuk tampilan). Semua halaman yang mengubah data santri (Bulk Edit, form edit) mengirim id_diniyah, id_formal, id_kamar ke API. Tampilan tabel, filter opsi, dan export memakai nama.", 'released_at' => '2026-03-03 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.4.1', 'role_id' => 18, 'title' => 'Data Ijin', 'changelog' => "Filter: Diniyah dan Formal memakai id (dropdown nilai = id, label = nama lembaga). Daerah dan Kamar filter tetap by nama. Tabel dan export: kolom Daerah, Kamar, Diniyah, Formal menampilkan nama dari API.\nUbah masal (Bulk Edit): kolom Diniyah/Formal pakai opsi rombel (id_diniyah, id_formal). Kolom Daerah-Kamar: pilih Daerah lalu Kamar, kirim id_kamar.\nEdit cepat (offcanvas): form edit santri seperti biodata UWABA – dropdown Daerah → Kamar (id_daerah, id_kamar), dropdown Diniyah/Formal (rombel, id_diniyah, id_formal), Gender dan Status Santri dropdown. Simpan kirim id_diniyah, id_formal, id_kamar.\nExport: tombol Export membuka offcanvas kanan untuk pilih kolom yang akan dieksport (seperti Manage Data UWABA); pilihan kolom disimpan di localStorage. Data export memakai nama daerah, kamar, diniyah, formal.", 'released_at' => '2026-03-03 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.4.1', 'role_id' => 19, 'title' => 'Data Ijin', 'changelog' => "Filter diniyah/formal by id; ubah masal pakai rombel dan id_kamar; offcanvas edit santri dengan dropdown daerah-kamar dan diniyah/formal; export via offcanvas pilih kolom.", 'released_at' => '2026-03-03 00:00:00'],

        // --- API 2.5.0 – Notifikasi & WatZap ---
        ['app' => 'api', 'version' => '2.5.0', 'role_id' => null, 'title' => 'API 2.5.0 – Notifikasi & WatZap', 'changelog' => "Pengaturan notifikasi WA (super_admin only):\n• Tabel app___settings (key-value): notification_provider (wa_sendiri | watzap). Migrasi 20260315000001.\n• GET/PUT /api/settings/notification-config: baca/simpan provider notifikasi.\nIntegrasi WatZap (api.watzap.id):\n• Config: WATZAP_API_URL, WATZAP_API_KEY, WATZAP_NUMBER_KEY (default ALL). Body kirim: api_key, number_key, phone_no, message (tanpa device_id).\n• WatzapService: proxy ke WatZap; sendMessage(phone, message, numberKey).\n• GET /api/watzap/status, GET /api/watzap/devices, POST /api/watzap/send (body: phone, message [, number_key ]). Semua endpoint watzap hanya super_admin.\nWhatsAppService:\n• getNotificationProvider(): baca dari app___settings. Jika provider = watzap → kirim lewat WatzapService (number_key ALL atau dari env); else kirim lewat WA server (WA_API_URL).\n• Semua notifikasi teks (daftar, PSB, pembayaran, auth, pengeluaran, chat) ikut setting: WA server sendiri atau WatZap.", 'released_at' => '2026-03-15 00:00:00'],

        // --- UWABA 6.4.2 – Setting Notifikasi & WatZap (super_admin) ---
        ['app' => 'uwaba', 'version' => '6.4.2', 'role_id' => 1, 'title' => 'Setting – Notifikasi & WatZap', 'changelog' => "Notifikasi (Setting → Notifikasi, hanya Super Admin):\n• Pilih provider notifikasi WA: WA server sendiri (koneksi di halaman WhatsApp, scan QR) atau WatZap (api.watzap.id).\n• Simpan dipakai seluruh aplikasi & API: daftar, PSB, pembayaran, auth, pengeluaran, chat mengikuti provider yang dipilih.\nWatZap (Setting → WatZap, hanya Super Admin):\n• Halaman kelola WatZap: tampil status konfigurasi backend (api_url, number_key).\n• Tes kirim pesan: nomor tujuan + isi pesan; optional number_key. Backend proxy ke WatZap (api_key + number_key ALL).\n• Link dokumentasi: API WatZap, menambahkan nomor WA untuk API.\nMenu: Notifikasi dan WatZap ditambah di grup Setting (menuConfig), requiresSuperAdmin: true. Route /settings/notifikasi, /settings/watzap dilindungi SuperAdminRoute.", 'released_at' => '2026-03-15 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.4.2', 'role_id' => null, 'title' => 'Notifikasi & WatZap', 'changelog' => "Setting → Notifikasi: pilih WA server sendiri atau WatZap (hanya Super Admin). Semua notifikasi WA (daftar, pembayaran, dll.) ikut setting.\nSetting → WatZap: status & tes kirim pesan lewat WatZap (hanya Super Admin).", 'released_at' => '2026-03-15 00:00:00'],

        // --- UWABA 6.5.6 (eBeddien) – Auth, Kalender offcanvas, Tema, Token 5 jam, Animasi flip ---
        ['app' => 'uwaba', 'version' => '6.5.6', 'role_id' => null, 'title' => 'Login, Token & Kalender', 'changelog' => "Token login: batas 5 jam dari terakhir digunakan (sliding). Lewat 5 jam wajib login lagi. Refresh token tetap disimpan (tanpa auto-login ke aplikasi).\nKalender (HP): tombol kalender di bawah layar (icon + label kecil, tanpa BG). Klik membuka offcanvas dari bawah dengan kepala bergelombang (animasi air), tombol tutup panah ke bawah. Kalender bisa diakses bagi yang pernah login (auth_ever_logged_in/refresh_token tetap).\nKalender (PC): offcanvas dari kiri; header dengan judul dan tombol X. Klik ikon kalender di strip pemisah membuka panel kalender dari kiri.", 'released_at' => '2026-03-17 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.5.6', 'role_id' => null, 'title' => 'Tema & Tombol Pemisah', 'changelog' => "Tema gelap/terang: icon tema dengan animasi flip saat ganti tema (desktop dan mobile).\nMode PC: tombol tema dan kalender dipindah ke garis vertikal pemisah kiri/kanan; icon tersusun vertikal dengan background bulat sesuai tema (putih/gelap).\nMode HP: tombol tema dan kalender di bawah, berjejer, style sama (icon + label kecil, tanpa BG).", 'released_at' => '2026-03-17 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.5.6', 'role_id' => null, 'title' => 'Animasi Halaman Auth', 'changelog' => "Login, Daftar, Lupa Password: saat ganti tema – logo flip ke kanan (AnimatePresence); input flip dengan scale (animasi flip-scale-2-hor-bottom). Satu wrapper untuk semua input agar animasi konsisten; kelas idle mereset transform agar animasi jalan tiap kali ganti tema; backface-visibility menghindari teks terbalik.", 'released_at' => '2026-03-17 00:00:00'],

        // --- Infrastruktur VPS – Port wa, wa2, live, live2 & Nginx ---
        ['app' => 'api', 'version' => '2.5.1', 'role_id' => null, 'title' => 'Infrastruktur – Port & Nginx VPS', 'changelog' => "Port dan .env di VPS diselaraskan:\n• wa (production): 3001 | wa2 (staging): 3003 | live (production): 3004 | live2 (staging): 3005.\n• Nginx: proxy wa2.alutsmani.id diperbaiki dari 3002 ke 3003 (sesuai .env wa2).\n• deploy/setup-wa-vps.ps1: semua referensi wa2 diubah dari port 3002 ke 3003 (template Nginx, pesan).\n• deploy-live-vps.ps1: teks pilihan deploy diperbaiki (Staging = 3005, Production = 3004). Tidak ada bentrok port antar wa, wa2, live, live2.", 'released_at' => '2026-03-17 00:00:00'],

        // --- Live server (Socket.IO presence) ---
        ['app' => 'live', 'version' => '1.0.0', 'role_id' => null, 'title' => 'Server Live (Socket.IO)', 'changelog' => "Server presence (Node + Express + Socket.IO):\n• Event: connect_user, connect_visitor, change_page, disconnect; daftar user online in-memory.\n• Admin: GET /admin/online (query secret); broadcast users_updated untuk real-time.\n• IP user dari header X-Forwarded-For / X-Real-IP (di belakang Nginx).\n• Deploy: setup-live-vps.ps1 (folder, Nginx, SSL), deploy-live-vps.ps1 (upload, npm install, PM2). Port: live 3004, live2 3005.", 'released_at' => '2026-03-17 00:00:00'],

        // --- Ebeddien (uwaba) – Super Admin Online, LiveSocketSync, liveServer.js ---
        ['app' => 'uwaba', 'version' => '6.5.7', 'role_id' => 1, 'title' => 'Super Admin – Online (Presence)', 'changelog' => "Menu Super Admin → Online (/super-admin/dashboard): daftar user aktif (nama/IP, halaman, waktu) real-time via Socket.IO event users_updated.\nLiveSocketSync: satu komponen di App.jsx, jalan di semua halaman (termasuk login); kirim connect_visitor (tanpa login) atau connect_user (setelah login). Server live menyimpan IP dari koneksi dan nama jika login.\nConfig liveServer.js: ebeddien.alutsmani.id → https://live.alutsmani.id, ebeddien2.alutsmani.id → https://live2.alutsmani.id; selain itu VITE_LIVE_SERVER_URL atau localhost:3004.", 'released_at' => '2026-03-17 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.5.7', 'role_id' => null, 'title' => 'Presence & Server Live', 'changelog' => "Fitur Online (Super Admin): lihat user aktif real-time. Koneksi ke server live (live.alutsmani.id / live2.alutsmani.id) via liveServer.js dan LiveSocketSync.", 'released_at' => '2026-03-17 00:00:00'],

        // --- API 2.6.0 – eBeddien / Deepseek: log ai___chat, kategori [label], saran training ---
        ['app' => 'api', 'version' => '2.6.0', 'role_id' => null, 'title' => 'API 2.6.0 – eBeddien & ai___chat', 'changelog' => "Deepseek / asisten eBeddien:\n• GET /deepseek/training-suggestions: saran cepat hanya dari tabel ai___training (pertanyaan acak), bukan dari training chat.\n• resolveUsersId: selaras JWT/sesi (users_id, pengurus.id_user, fallback user_id); nilai wajib ada di users.id untuk FK ai___chat.users_id.\n• persist ai___chat: user_name/email dari JOIN users + pengurus.nama + santri.nama (bukan kolom nama di users — perbaikan error Unknown column nama).\n• Kategori: model diinstruksikan mengakhiri jawaban dengan [Nama Kategori]; ekstraksi dari [...] di akhir (atau pasangan terakhir) ke kolom category; fallback Lainnya.\n• AiTrainingRagHelper: instruksi format [kategori] di system prompt & merge prompt (mode proxy).\n• Log error persist: SQLSTATE untuk diagnosis.", 'released_at' => '2026-03-21 00:00:00'],

        // --- UWABA 6.5.8 (eBeddien) – Chat AI layout, tema primary, logo, pelatihan ---
        ['app' => 'uwaba', 'version' => '6.5.8', 'role_id' => null, 'title' => 'eBeddien – Chat AI & Pelatihan', 'changelog' => "Chat AI (/chat-ai):\n• Layout ChatAiLayout: satu kartu + slot header + Outlet — header tidak remount penuh saat pindah rute.\n• Rute bersarang: index = chat utama; /training & /training-chat (Super Admin) di bawah path sama.\n• Header: warna tema primary (teal), logo putih seperti sidebar (ikon + wordmark), tanpa subtitle email Utama/Alternatif.\n• Tombol kirim, gelembung chat, saran cepat: gaya primary; latar area primary-50.\n• Pelatihan: Bank Q&A & Training Chat memakai header training yang sama; subtitle pelatihan tanpa email.\n• Saran cepat: hanya dari bank Q&A server (selaras API).", 'released_at' => '2026-03-21 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.5.8', 'role_id' => 1, 'title' => 'eBeddien – Super Admin pelatihan', 'changelog' => "Super Admin: submenu /chat-ai/training (Bank Q&A) dan /chat-ai/training-chat dari header pelatihan (NavLink), tanpa duplikasi chrome layout.", 'released_at' => '2026-03-21 00:00:00'],

        // --- API 2.6.1 – Ijin: id INT AUTO_INCREMENT ---
        ['app' => 'api', 'version' => '2.6.1', 'role_id' => null, 'title' => 'API 2.6.1 – Ijin (ID otomatis)', 'changelog' => "Tabel santri___ijin: kolom id menjadi INT AUTO_INCREMENT (migrasi 20260321000007).\nInsert ijin tanpa id manual; id dari lastInsertId(). Detail/route memakai id integer.\nNomor surat di aplikasi: format IJN-{id}/PSA/{bulan.tahun hijriyah} dari tanggal_dibuat (konversi kalender).", 'released_at' => '2026-03-21 12:00:00'],

        // --- UWABA 6.5.9 (eBeddien) – Print surat ijin, lama hari inklusif, margin per salinan ---
        ['app' => 'uwaba', 'version' => '6.5.9', 'role_id' => 18, 'title' => 'Ijin – Print surat & form lama', 'changelog' => "Print surat ijin (landscape A4, dua salinan): nomor surat rata tengah; aksen pita di atas blok nomor; margin isi diatur per salinan (kolom kiri & kanan), bukan satu padding untuk seluruh lembar.\nOffcanvas print: ribbon bergaya Office (Margin halaman) dengan Atas/Bawah/Kiri/Kanan (mm) dan preset standar.\nKolom Alasan selalu tercetak (kosong tampil —).\nLama ijin: hitung hari kalender inklusif — hari pertama dan terakhir dihitung (contoh Ahad–Senin = 2 hari); via tanggal Masehi dari konversi Hijriyah.", 'released_at' => '2026-03-21 12:00:00'],
        ['app' => 'uwaba', 'version' => '6.5.9', 'role_id' => 19, 'title' => 'Ijin – Print & lama hari', 'changelog' => "Print surat ijin: margin per salinan, ribbon margin, nomor tengah + pita, Alasan selalu di surat. Lama ijin otomatis inklusif (Ahad–Senin = 2 hari).", 'released_at' => '2026-03-21 12:00:00'],
        ['app' => 'uwaba', 'version' => '6.5.9', 'role_id' => null, 'title' => 'Ijin – Cetak & perhitungan hari', 'changelog' => "Surat ijin cetak: margin per kolom salinan, pengaturan ribbon, nomor & pita, Alasan selalu ditampilkan.\nLama ijin: jumlah hari inklusif.\nBackend: id ijin AUTO_INCREMENT (API 2.6.1).", 'released_at' => '2026-03-21 12:00:00'],

        // --- API 2.6.2 – Ijin: kamar-options & rombel-options (role ijin) ---
        ['app' => 'api', 'version' => '2.6.2', 'role_id' => null, 'title' => 'API 2.6.2 – Ijin (dropdown kamar & rombel)', 'changelog' => "Endpoint khusus admin_ijin / petugas_ijin (tidak perlu akses /api/daerah-kamar super_admin atau /api/pendaftaran PSB):\n• GET /api/ijin/kamar-options — daftar kamar aktif dari daerah___kamar JOIN daerah (daerah_nama, daerah_kategori/kategori). Query opsional: id_daerah, status.\n• GET /api/ijin/rombel-options?jenis=diniyah|formal — daftar rombel (sama logika dengan pendaftaran/rombel-options).\nRoute: api/routes/21_ijin_boyong.php.", 'released_at' => '2026-03-21 20:00:00'],

        // --- UWABA 6.6.0 (eBeddien) – Data Ijin: id_kamar + kategori; print surat; margin cetak global ---
        ['app' => 'uwaba', 'version' => '6.6.0', 'role_id' => 18, 'title' => 'Ijin – Form santri & print surat', 'changelog' => "Detail santri (offcanvas): edit kamar lewat id_kamar saja; dropdown dari ijinAPI.getKamarOptions (kategori daerah + nama daerah + nama kamar). Rombel Diniyah/Formal dari ijinAPI.getRombelOptions.\nPrint surat ijin: Ahad menggantikan Minggu pada teks tanggal (Hijri/Masehi) dan tanggal tanda tangan.\nCetak: A4 landscape, dua salinan kiri–kanan; pemisah garis putus pada kolom kiri; layout grid minmax(0,1fr) supaya teks tidak tembus kolom/pembatas kertas.\nSurat: baris Diniyah, Formal, Kamar + id_diniyah/id_formal/id_kamar; perbaikan margin (@page global index.css → 0, padding laporan di .laporan-container).\nisi-surat: lebar mengisi kolom (tanpa blok sempit terpusat); padding kiri diperketat.", 'released_at' => '2026-03-21 20:00:00'],
        ['app' => 'uwaba', 'version' => '6.6.0', 'role_id' => 19, 'title' => 'Ijin – Form santri & print surat', 'changelog' => "Form kamar id_kamar + kategori/rombel via API /api/ijin/*-options.\nPrint: Ahad, landscape duplex, grid kolom, margin cetak & isi surat diperbaiki (selaras 6.6.0 admin_ijin).", 'released_at' => '2026-03-21 20:00:00'],
        ['app' => 'uwaba', 'version' => '6.6.0', 'role_id' => null, 'title' => 'Cetak & Ijin (ringkas)', 'changelog' => "API 2.6.2: GET /api/ijin/kamar-options, /api/ijin/rombel-options untuk petugas ijin.\nFrontend: form Data Ijin memakai endpoint tersebut; print surat ijin diperbaiki (Ahad, layout duplex, margin).\nGlobal: @page print margin 0 + padding laporan (index.css).", 'released_at' => '2026-03-21 20:00:00'],

        // --- API 2.6.3 – Lembaga: kolom logo_path, upload/serve/hapus logo (PNG) ---
        ['app' => 'api', 'version' => '2.6.3', 'role_id' => null, 'title' => 'API 2.6.3 – Logo Lembaga', 'changelog' => "Lembaga:\n• Migrasi 20260322000001: kolom logo_path (VARCHAR 500, nullable) — path relatif uploads/lembaga/*.png.\n• LembagaLogoController: POST /api/lembaga/{id}/logo (multipart file), DELETE /api/lembaga/{id}/logo, GET /api/lembaga/serve-logo?path=…\n• Hanya PNG (image/png + validasi getimagesize IMAGETYPE_PNG), maks. 2 MB; file disimpan di uploads/lembaga/; ganti logo menghapus file lama.\n• Hapus lembaga: file logo ikut dihapus dari disk.\n• Akses: upload/hapus logo super_admin; serve-logo + GET lembaga: super_admin & admin_uwaba.", 'released_at' => '2026-03-22 00:00:00'],

        // --- UWABA 6.6.1 (eBeddien) – Halaman Lembaga: unggah logo PNG ---
        ['app' => 'uwaba', 'version' => '6.6.1', 'role_id' => 1, 'title' => 'Pengaturan – Lembaga (logo)', 'changelog' => "Halaman Lembaga (Pengaturan):\n• Kolom logo per lembaga: unggah file PNG (maks. 2 MB di server) dari modal edit; hapus logo tanpa menghapus lembaga.\n• Kartu daftar menampilkan thumbnail logo jika sudah diunggah.\n• Logo baru bisa ditambahkan setelah lembaga disimpan (tambah lembaga dulu, lalu edit untuk upload).\n• API: lembagaAPI.uploadLogo, deleteLogo, fetchLogoBlobUrl (autentikasi).", 'released_at' => '2026-03-22 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.6.1', 'role_id' => 2, 'title' => 'Lembaga – Tampilan logo', 'changelog' => "Daftar lembaga menampilkan thumbnail logo (PNG) jika lembaga sudah punya logo. Pengunggahan dan penghapusan logo hanya Super Admin (halaman Pengaturan → Lembaga).", 'released_at' => '2026-03-22 00:00:00'],
        ['app' => 'uwaba', 'version' => '6.6.1', 'role_id' => null, 'title' => 'Logo lembaga (ringkas)', 'changelog' => "Backend API 2.6.3: logo lembaga (PNG) di kolom logo_path, endpoint upload/serve/hapus.\neBeddien 6.6.1: halaman Lembaga — thumbnail di kartu; upload/hapus logo untuk Super Admin.", 'released_at' => '2026-03-22 00:00:00'],
        // --- API 2.6.4 – Admin ai___chat: dashboard, riwayat, filter & edit ---
        ['app' => 'api', 'version' => '2.6.4', 'role_id' => null, 'title' => 'API 2.6.4 – Admin ai___chat', 'changelog' => "Super_admin (is_real_super_admin) untuk kelola data chat AI (ai___chat):\n• GET /api/deepseek/admin/ai-dashboard?days=7|30|90: agregasi metrik (total pesan, user unik, kategori teratas, volume harian, web vs whatsapp).\n• GET /api/deepseek/admin/chat-log/meta: daftar kategori unik + pengguna untuk filter.\n• GET /api/deepseek/admin/chat-log?page=&limit=&search=&days=&users_id=&category=: daftar log chat untuk riwayat.\n• PATCH /api/deepseek/admin/chat-log/{id}: edit user_message, jawaban (reply/thinking) dan penyimpanan ai_response penuh serta category (mengikuti pola [kategori]).", 'released_at' => '2026-03-26 00:00:00'],
        // --- UWABA 6.6.2 (eBeddien) – Chat AI: dashboard admin + riwayat edit & promo ke Bank ---
        ['app' => 'uwaba', 'version' => '6.6.2', 'role_id' => null, 'title' => 'Chat AI – Dashboard & Riwayat', 'changelog' => "eBeddien Super Admin untuk Chat AI (/chat-ai):\n• Dashboard (/chat-ai/dashboard): ringkasan metrik + grafik (Chart.js) + top user + kategori teratas.\n• Riwayat (/chat-ai/riwayat): UI modern dengan toolbar meniru halaman Pengurus (search + filter kategori + filter user + rentang waktu + items per page + pagination).\n• Drawer detail: edit pertanyaan/jawaban (reply) dan thinking, simpan ke ai___chat via PATCH.\n• Button \"Tambah ke Bank Q&A\": kategori dropdown diambil dari Bank Q&A dan bisa menambah kategori baru (opsi + kategori baru… seperti UI Bank Q&A).\n• Header pelatihan super admin: link Dashboard dan Riwayat ditambahkan di header (tanpa sidebar).", 'released_at' => '2026-03-26 00:00:00'],
        // --- API 2.6.5 – Chat realtime + PWA push ---
        ['app' => 'api', 'version' => '2.6.5', 'role_id' => null, 'title' => 'API 2.6.5 – Chat realtime + Push PWA', 'changelog' => "UserChatController: setelah simpan pesan chat private (users.id), backend memicu Web Push ke penerima agar notifikasi tetap masuk saat aplikasi tidak dibuka.\nPushNotificationService: tambah sendToUserIds() untuk mapping users.id -> pengurus.id -> pengurus___subscription.\nPayload push chat membawa sender_name, preview pesan, dan url langsung ke /chat?u=<from_user_id>.\nSinkron env: VAPID_PUBLIC_KEY/VAPID_PRIVATE_KEY/VAPID_SUBJECT di API dan VITE_VAPID_PUBLIC_KEY di frontend.", 'released_at' => '2026-03-27 00:00:00'],
        // --- eBeddien 6.6.3 – Rebranding nama aplikasi + notifikasi chat global ---
        ['app' => 'ebeddien', 'version' => '6.6.3', 'role_id' => null, 'title' => 'Rebranding eBeddien & chat notifier', 'changelog' => "Konsistensi nama aplikasi di changelog: eBeddien menjadi nama resmi (legacy UWABA tetap kompatibel di API).\nChat notifier global berbasis websocket: muncul di semua halaman.\nMobile: banner atas. Desktop: toast kanan bawah. Quick reply langsung dari notifikasi dengan ACK send_message_result (sukses/gagal).\nAnimasi notifikasi halus: masuk/keluar; di mobile exit ke atas, di desktop exit ke kanan. Tombol tutup disederhanakan jadi ikon X.\nPerbaikan aset staging: favicon/icon dan manifest screenshot diarahkan konsisten ke https://alutsmani.id/gambar (hindari 404 ke subdomain staging).", 'released_at' => '2026-03-27 00:00:00'],

        // --- API 2.6.6 – WebAuthn (passkey) ---
        ['app' => 'api', 'version' => '2.6.6', 'role_id' => null, 'title' => 'API 2.6.6 – WebAuthn (passkey)', 'changelog' => "Login & profil: WebAuthn (passkey / sidik jari) dengan web-auth/webauthn-lib (PHP 8.1+).\nMigrasi: kolom webauthn_* di users, tabel webauthn_challenges; password_login_count untuk interval prompt daftar passkey setelah login password.\nEndpoint v2: POST/GET register & login options/verify, GET status (username). CSRF dikecualikan untuk upacara WebAuthn.\nAuth v2: finalize session, show_passkey_prompt sesuai aturan backend.", 'released_at' => '2026-03-27 12:00:00'],

        // --- eBeddien 6.6.4 – Passkey, login & profil ---
        ['app' => 'ebeddien', 'version' => '6.6.4', 'role_id' => null, 'title' => 'eBeddien – Passkey & login', 'changelog' => "Login: login passkey (ikon sidik jari di samping tombol Masuk); username terakhir disimpan per perangkat agar passkey dicek otomatis.\nModal pengingat daftar passkey setelah login password (interval server).\nProfil → Keamanan: daftarkan passkey.\n@simplewebauthn/browser; endpoint status WebAuthn publik tanpa terblokir token lama di halaman login.", 'released_at' => '2026-03-27 12:00:00'],

        // --- API 2.7.0 – Akses eBeddien lewat role___fitur + perbaikan endpoint ---
        ['app' => 'api', 'version' => '2.7.0', 'role_id' => null, 'title' => 'API 2.7.0 – Fitur menu & middleware akses', 'changelog' => "Akses staff eBeddien: EbeddienFiturMiddleware (selector app___fitur / role___fitur, fallback role legacy jika belum ada assignment).\nBanyak route dipindah dari RoleMiddleware ke selector di EbeddienFiturAccess (PSB, tarbiyah, UGT, ijin, keuangan, kalender, cashless, umroh, dll.).\nGET /user/list-super-admin-uwaba: selector digabung financeMenus agar admin_lembaga & peran dengan menu pengeluaran tidak 403 saat notifikasi WA rencana.\nGET /profil/total-pemasukan-pengeluaran: route terpisah dengan profilSaldoKeuanganSelectors (UWABA + financeMenus); legacy admin_lembaga.\nKalender Google / hari penting: selector tanpa menu.kalender publik agar tidak lolos berdasarkan menu umum semua role.\nRoleFiturMenuSeed: jika meta requiresRole + requiresPermission, keduanya wajib (mis. dashboard keuangan + manage_finance).\nAppFiturMenuSeed + migrasi 20260428120000: menu Umroh requiresRole menyertakan admin_uwaba, petugas_uwaba, admin_umroh, petugas_umroh, super_admin (selaras API & frontend).\nJalankan ulang RoleFiturMenuSeed setelah migrasi Umroh.", 'released_at' => '2026-03-28 00:00:00'],

        // --- API 2.7.1 – Seed aksi halaman (staging: migrate sebelum menu kosong) ---
        ['app' => 'api', 'version' => '2.7.1', 'role_id' => null, 'title' => 'API 2.7.1 – MenuActionsFiturSeed', 'changelog' => "Baris app___fitur type=action (aksi halaman eBeddien) dipindahkan ke seed MenuActionsFiturSeed agar staging/production tetap terisi walau deploy menjalankan phinx migrate sebelum menu ada (migrasi action lama skip insert jika parent menu belum ada).\nUrutan seed: AppFiturMenuSeed → MenuActionsFiturSeed → RoleFiturMenuSeed (atau seed:run tanpa -s).\nSetelah deploy pertama kali file ini: jalankan phinx seed:run -s MenuActionsFiturSeed lalu -s RoleFiturMenuSeed jika role___fitur untuk action belum lengkap.", 'released_at' => '2026-03-28 12:00:00'],

        // --- API 2.7.2 – Selector middleware & katalog menu dari DB ---
        ['app' => 'api', 'version' => '2.7.2', 'role_id' => null, 'title' => 'API 2.7.2 – RBAC selector & menu catalog', 'changelog' => "Tabel ebeddien_fitur_selector: daftar kode fitur per endpoint (EbeddienFiturMiddleware) diisi dari seed EbeddienFiturSelectorSeed — boleh disesuaikan di DB tanpa ubah PHP; fallback tetap ada di EbeddienFiturAccessDefinitions.\nGET /api/v2/fitur/ebeddien/menu-catalog: semua menu eBeddien dari app___fitur untuk menyusun UI frontend dari database.\nFrontend eBeddien: fetch paralel fitur-menu + menu-catalog; sidebar/expanded nav pakai katalog + kode user jika items /me kosong; Header title groups & Beranda/Semua Menu mengutamakan katalog DB.", 'released_at' => '2026-03-28 18:00:00'],

        // --- eBeddien 6.6.5 – Keuangan, Umroh, UI akses ---
        ['app' => 'ebeddien', 'version' => '6.6.5', 'role_id' => null, 'title' => 'eBeddien – Keuangan & hak akses', 'changelog' => "menuConfig: menu Umroh selaras backend (UWABA + admin/petugas umroh).\nusePengeluaranFiturAccess: fallback hasKeuangan termasuk admin_lembaga.\nEdit rencana pengeluaran: tombol Draft / Simpan hanya ditampilkan jika ada hak (bukan hanya disabled).\nDetailOffcanvas rencana: tombol kirim ulang notifikasi WA hanya jika ada admin terpilih.\nHeader saldo Keuangan: memakai endpoint profil total pemasukan–pengeluaran yang sudah diselaraskan API 2.7.0.", 'released_at' => '2026-03-28 00:00:00'],

        // --- Daftar 2.2.0 – cache halaman, invalidasi, pembayaran, logout penuh, info publik ---
        ['app' => 'daftar', 'version' => '2.2.0', 'role_id' => null, 'title' => 'Cache & data lokal (Dashboard, Biodata, Berkas, Pembayaran)', 'changelog' => "Hidrasi dari localStorage: Dashboard (status langkah & ringkasan berkas), Biodata (snapshot form + meta sinkron), halaman Berkas (daftar berkas), halaman Pembayaran (registrasi, rincian item, bukti TF, riwayat transaksi) agar kembali ke halaman terasa lebih cepat.\nInvalidasi terkoordinasi: setelah simpan biodata → cache dashboard & pembayaran dibersihkan; setelah mutasi berkas atau pembayaran (termasuk iPayMu di offcanvas) → dashboard ikut di-invalidate agar progres tidak basi.\nPembayaran: offcanvas daftar pembayaran memakai satu sumber data dari halaman induk (satu rangkaian getTransaksi lewat refetch), tanpa permintaan ganda.\nDashboard: tombol «Segarkan» untuk memaksa muat ulang progres dari server.", 'released_at' => '2026-03-29 12:00:00'],
        ['app' => 'daftar', 'version' => '2.2.0', 'role_id' => null, 'title' => 'Logout, sesi habis & keamanan data perangkat', 'changelog' => "Logout: seluruh localStorage dan sessionStorage dikosongkan; Cache Storage API (PWA) dibersihkan bila didukung browser; reset store tahun ajaran, mode tampilan biodata, dan tema (mengikuti preferensi sistem); event daftar:logout untuk membersihkan state React (mis. perubahan belum disimpan).\nRespons 401 dari API: pembersihan yang sama (selaras dengan logout) sebelum redirect ke login.\nCatatan: cookie sesi httpOnly hanya bisa diakhiri dari server bila backend menyediakan endpoint logout cookie.", 'released_at' => '2026-03-29 12:00:00'],
        ['app' => 'daftar', 'version' => '2.2.0', 'role_id' => null, 'title' => 'Login & informasi pendaftaran', 'changelog' => "Offcanvas «Info pendaftaran» (desktop & mobile): tautan «Info lebih lanjut» ke https://pendaftaran.alutsmani.id dibuka di tab baru.\nVersi aplikasi tampil di login (mobile) dan form masuk (desktop) mengikuti APP_VERSION.", 'released_at' => '2026-03-29 12:00:00'],
        ['app' => 'daftar', 'version' => '2.2.0', 'role_id' => null, 'title' => 'Biodata, berkas & backend registrasi (ringkas)', 'changelog' => "Biodata: mode baca setelah simpan, indikator sumber data terbaru (tanggal update santri/registrasi), alur draft dan unsaved changes diselaraskan.\nBackend API (pendaftaran): perbaikan simpan/update registrasi agar tidak bentrok constraint unik tahun ajaran pada tabel registrasi (satu baris konsisten per konteks tahun).", 'released_at' => '2026-03-29 12:00:00'],
        // --- API 2.6.7 / eBeddien 6.6.6 / Daftar 2.2.4 – hardening, alert error, role akses ---
        ['app' => 'api', 'version' => '2.6.7', 'role_id' => null, 'title' => 'API 2.6.7 – Hardening log & alert error WA', 'changelog' => "Hardening observability:\n• Noise log bootstrap dimatikan default (aktifkan opsional via API_LOG_BOOTSTRAP=true).\n• Verbose log auth/role dimatikan default; toggle via API_VERBOSE_AUTH_LOG dan API_VERBOSE_ROLE_LOG.\nAlert error WhatsApp:\n• Notifikasi fatal/unhandled 5xx ke WA (nomor default 082232999921), dengan anti-spam 60 detik.\n• Prioritas kirim lewat WA server sendiri; fallback ke WatZap jika gagal.\n• Konfigurasi env: ERROR_ALERT_ENABLED, ERROR_ALERT_WA_NUMBER, ERROR_ALERT_PROVIDER.\nEndpoint tes:\n• POST /api/settings/error-alert/test (super_admin) untuk kirim pesan tes alert.\n• Response memuat wa_health (reachable, baileys_status) untuk diagnosis cepat koneksi WA server.", 'released_at' => '2026-04-08 00:00:00'],
        ['app' => 'ebeddien', 'version' => '6.6.6', 'role_id' => null, 'title' => 'eBeddien 6.6.6 – Akses role/permission & UI notifikasi', 'changelog' => "Role & akses frontend:\n• Helper akses diperluas (UWABA, PSB, Umroh, Ijin, Boyong) berbasis permission JWT + fallback role.\n• RoleRoute, Navigation, Sidebar, AdminRoute, PermissionRoute diselaraskan agar permission-aware dan redirect fallback konsisten.\n• Redirect unauthorized guard lama diarahkan ke /beranda (bukan root).\nNotifikasi settings:\n• Tambah UI \"Tes Alert Error WA\" di halaman Setting → Notifikasi (nomor + pesan opsional + status kirim).\nHeader:\n• Dropdown user ditambah menu Chat dan eBeddien AI.\n• Menu eBeddien mengarah ke /chat-ai dengan ikon yang disesuaikan.", 'released_at' => '2026-04-08 00:00:00'],
        ['app' => 'daftar', 'version' => '2.2.4', 'role_id' => null, 'title' => 'Daftar 2.2.4 – Sinkron versi backend', 'changelog' => "Sinkronisasi informasi versi aplikasi:\n• APP_VERSION dinaikkan ke 2.2.4.\n• BACKEND_VERSION diselaraskan ke API 2.6.7 agar tampilan versi antar aplikasi konsisten saat deploy batch.", 'released_at' => '2026-04-08 00:00:00'],

        // --- API 2.6.8 – Pengeluaran: notif draft (PWA+WA), perbaikan status ket ---
        ['app' => 'api', 'version' => '2.6.8', 'role_id' => null, 'title' => 'API 2.6.8 – Rencana draft: notifikasi & ket', 'changelog' => "Pengeluaran / rencana draft:\n• Saat simpan draft (create & update): notifikasi push PWA ke pengurus berhak (konteks draft) + WhatsApp ke role dengan aksi notif draft (satu lembaga), penyimpan dikecualikan; pengiriman dijadwalkan setelah response (DeferredHttpTask).\n• RencanaPengeluaranWaHelper::buildDraftSavedMessage — teks WA dengan link tab draft.\n• Perbaikan bug: edit draft lalu simpan tidak lagi mengubah ket menjadi «di edit» (pindah ke tab rencana); update nominal mempertahankan draft; ajuan dari draft ke pending tetap pending bila baris awal draft.\n• Helper penerima WA draft: filter pengurus eligible (aksi draft notif + nomor WA).\nMigrasi terkait (jalankan phinx migrate): 20260405120100_pengeluaran_terima_notif_wa, 20260411130000_pengeluaran_draft_wa_notif_action (dan seed MenuActionsFiturSeed / RoleFiturMenuSeed jika perlu assignment role).", 'released_at' => '2026-04-10 00:00:00'],

        // --- eBeddien 6.6.7 – Pengeluaran: tab URL, daftar draft tanpa offcanvas detail ---
        ['app' => 'ebeddien', 'version' => '6.6.7', 'role_id' => null, 'title' => 'eBeddien 6.6.7 – Pengeluaran (tab & draft)', 'changelog' => "Halaman Keuangan → Pengeluaran:\n• Klik tab Rencana / Pengeluaran / Draft memperbarui query ?tab= di URL (replace) agar state selaras dengan bookmark dan deep link.\n• Efek sinkron tab dari URL hanya memantau perubahan nilai query tab (bukan seluruh searchParams) — menghindari loncat ke tab Draft saat membuka detail rencana dari daftar.\n• Tab Draft: baris daftar tidak lagi membuka offcanvas detail (tanpa tombol edit/approve/tolak konteks rencana); hanya tombol Edit (ke halaman edit) dan Hapus.\n• URL ?tab=draft&rencana=… dibersihkan (hapus rencana) agar tidak membuka offcanvas approve/tolak di konteks draft.\nBACKEND_VERSION diselaraskan ke API 2.6.8.", 'released_at' => '2026-04-10 00:00:00'],

        ['app' => 'daftar', 'version' => '2.2.5', 'role_id' => null, 'title' => 'Daftar 2.2.5 – Sinkron versi backend', 'changelog' => "BACKEND_VERSION diselaraskan ke API 2.6.8 (selaras config.php).", 'released_at' => '2026-04-10 00:00:00'],
    ];

    public function run(): void
    {
        $seen = [];
        foreach ($this->entries as $row) {
            $key = $row['app'] . '|' . $row['version'];
            if (!isset($seen[$key])) {
                $seen[$key] = true;
                $this->execute(sprintf(
                    "DELETE FROM app_version_changelog WHERE app = %s AND version = %s",
                    $this->getAdapter()->getConnection()->quote($row['app']),
                    $this->getAdapter()->getConnection()->quote($row['version'])
                ));
            }
        }
        $table = $this->table('app_version_changelog');
        $table->insert($this->entries);
        $table->saveData();
    }
}
